# Generated by Django 3.2.6 on 2021-09-09 05:13

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=articles.models.articles_image_path),
        ),
    ]
